version: '3.8'
services:
  app:
    build: 
      context: ./backend/commander
    container_name: commander-app
    ports:
      - "5000:5000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app_network

  worker:
    build:
      context: ./backend/soldier  
    # container_name: soldier-app
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    deploy:
      replicas: 3
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    # ports:
    #   - "6379:6379"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
      build:
        context: ./frontend  
      container_name: frontend-app
      ports:
        - "3000:3000"  
      depends_on:
        - app  
      networks:
        - app_network

networks:
  app_network:
    driver: bridge
